@include('vistas_principales.shared.modulo-crud', [
    'title' => 'Seguimientos de frasco',
    'subtitle' => 'Registra y consulta el avance de germinación de los frascos bajo tu responsabilidad.',
    'items' => $seguimientos ?? collect(),
    'routeBase' => 'encargado.seguimientos-frasco',
    'entitySingular' => 'Seguimiento',
    'entityPlural' => 'Seguimientos',

    'columns' => [
        ['label' => 'Incubadora', 'key' => 'frasco.lote.posicion.incubadora.nombre'],
        ['label' => 'Lote', 'key' => 'frasco.lote.codigo_lote'],
        ['label' => 'Frasco', 'key' => 'frasco.numero_frasco', 'size' => 'short'],
        ['label' => 'Especie', 'key' => 'frasco.lote.especie.nombre_comun'],
        ['label' => 'Fecha', 'key' => 'fecha_revision'],
        ['label' => 'Germinadas', 'key' => 'semillas_germinadas', 'size' => 'short'],
        ['label' => 'Altura promedio', 'key' => 'altura_promedio_cm', 'size' => 'short'],
        ['label' => 'Estado', 'key' => 'estado.nombre', 'size' => 'short'],
        ['label' => 'Registró', 'key' => 'user.name'],
        ['label' => 'Observaciones', 'key' => 'observaciones', 'wrap' => true],
    ],

    'fields' => [
        [
            'name' => 'frasco_id',
            'label' => 'Frasco',
            'type' => 'select',
            'required' => true,
            'options' => $frascosOptions ?? [],
            'option_value' => 'id',
            'option_label' => 'etiqueta',
        ],
        [
            'name' => 'fecha_revision',
            'label' => 'Fecha de revisión',
            'type' => 'date',
            'required' => true,
        ],
        [
            'name' => 'semillas_germinadas',
            'label' => 'Semillas germinadas',
            'type' => 'number',
            'required' => true,
        ],
        [
            'name' => 'altura_promedio_cm',
            'label' => 'Altura promedio (cm)',
            'type' => 'number',
        ],
        [
            'name' => 'estado_frasco_id',
            'label' => 'Estado del frasco',
            'type' => 'select',
            'required' => true,
            'options' => $estados ?? [],
            'option_value' => 'id',
            'option_label' => 'nombre',
        ],
        [
            'name' => 'observaciones',
            'label' => 'Observaciones',
            'type' => 'textarea',
            'rows' => 4,
        ],
    ],

    'canCreate' => true,
    'canEdit' => false,
    'canDelete' => false,
    'canShow' => false,
    'showAsPage' => false,
])
